config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :bookings
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :musics
  root to: "musics#index"
  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/music.rb
class Music < ActiveRecord::Base
  # include ParseModel::Model
	mount_uploader :attachment, AttachmentUploader
	def set_success(format, opts)
    self.success = true
  end
  def parse
    file = "/Users/adityanarayan/Desktop/orel/Hubb_Music/uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  require 'rest_client'
  class << self
    attr_accessor :BOUNDARY
  end

  before_action :set_music, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def boundary
    self.class.BOUNDARY = "AaB03x"
  end

  def create_parse_user
    name =  "name"
    password =  "password"
    email = "example@email.com"
    puts name, password, email
    uri = URI('https://api.parse.com/1/users')
    req = Net::HTTP::Post.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    req.body = {
        :username => name,
        :password => password,
        :email => email,
        :music => "hello",
    }.to_json
    http.use_ssl = true
    response = http.request(req)
    puts response.body
    objID = response.body.split(',')[1].split("\"" )[3]
    sesstoken = response.body.split(',')[2].split("\"")[3]
    puts objID
    puts sesstoken
  end


  def login_parse_user
    username =  @parseuser.name
    password =  @parseuser.password
    puts @parseuser.password
    uri = URI('https://api.parse.com/1/login?username=username&password=password')
    req = Net::HTTP::Get.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(req)
    puts response.body
    #not working
  end

  def validate_user_session
    uri = URI('https://api.parse.com/1/users/me')
    req = Net::HTTP::Get.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['X-Parse-Session-Token'] = "VpRMPOhRHZI0fM1xfXeDaaQHP"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(req)
    puts response.body
  end

  def create_base_object
    uri = URI('https://api.parse.com/1/classes/PlayerProfile/')
    req = Net::HTTP::Post.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(req)
    puts response.body
    obj = response.body.split(',')[1].split("\"" )[3]
    puts obj
    # associate_obj_with_a_user
    uri_two = URI("https://api.parse.com/1/classes/PlayerProfile/HxiRjCe0Qx")
    req = Net::HTTP::Put.new(uri_two)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    payload = {
        :user => {
            :__op => "AddRelation",
            :objects => [{
                :__type => "Pointer",
                :className => "PlayerProfile",
                :objectId => obj,
            }],
        }
    }
    req.body = payload.to_json
    http.use_ssl = true
    response = http.request(req)
    puts response.body
    # upload_file_to_parse
    file = "/Users/adityanarayan/Desktop/orel/Hubb_Music/public/#{@music.attachment.url}"
    puts file
    request = RestClient::Request.new(
        :method => :post,
        :url => 'https://api.parse.com/1/files/test',
        :headers => {
            :'X-Parse-Application-Id' => "cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW",
            :'X-Parse-REST-API-Key' => "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd",
            :'Content-Type' => 'audio/mpeg'
        },
        :payload => {
            :multipart => true,
            :file => File.new(file, 'rb'),
        })
    response =  request.execute
    puts response.body
    parsed_json = JSON(response)
    puts parsed_json["name"]
    payload = {
        :name => "#{@music.title}",
        :url => {
            :__type => "File",
            :name => parsed_json["name"]

        }
    }
    uri = URI('https://api.parse.com/1/classes/PlayerProfile/')
    req = Net::HTTP::Post.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    req.body = payload.to_json
    http.use_ssl = true
    http.request(req)
    puts response.body
    # associate_file_with_object
     uri = URI('https://api.parse.com/1/classes/PlayerProfile/7vlDYp5GfO')
    req = Net::HTTP::Put.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    payload = {
            :music => {
                :__type => "File",
                :name => parsed_json,
            }
     }
     req.body = payload.to_json
    http.use_ssl = true
    response = http.request(req)
    puts response.body
  end

  def check_users
    uri = URI('https://api.parse.com/1/users/QFlWE01NWM')
    req = Net::HTTP::Get.new(uri)
    req['X-Parse-Application-Id'] ="cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW"
    req['X-Parse-REST-API-Key'] = "nd8iZTjMxdTcqHSNMuGign8RpvirPaLHcs8gLHKd"
    req['Content-Type'] = 'application/json'
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(req)
    puts response.body
  end


  def index
    @musics = Music.all
    respond_with(@musics)
  end

  def show
    respond_with(@music)
  end

  def new
    @music = Music.new
    respond_with(@music)
  end

  def edit
  end

  def create
    @music = Music.new(music_params)
    # render json:params
      if  @music.save
        create_base_object
        # associate_with_a_user
        # upload_file_to_parse
        # associate_file_with_object
        redirect_to musics_path, notice: "The video has been uploaded!"
      else
        respond_with(@music)
      end
  end

  def update
    @music.update(music_params)
    respond_with(@music)
  end

  def destroy
    @music.destroy
    respond_with(@music)
  end

  private
    def set_music
      @music = Music.find(params[:id])
    end

    def music_params
      params.require(:music).permit(:title, :description, :name, :attachment)
    end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<script src="//www.parsecdn.com/js/parse-1.3.5.min.js"></script>

<script type="text/javascript">
Parse.initialize("cg6iHL8YwU72M53e8U0XZkNeE698IVbBDo2o5LEW", "LUZs1QWRy09F02MfCYp4HMMmc0awCsyRpzxlrEqb");
</script>

<script>
var TestObject = Parse.Object.extend("TestObject");
var testObject = new TestObject();
testObject.save({foo: "bar"}).then(function(object) {
  alert("yay! it worked");
});

</script>


<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2
      <ul>
      <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<br />
<table class="rwd-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.title %></td>
        <td><%= music.description %></td>
        <td><%= link_to 'Play my song', music.attachment.url %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>



<p>&larr; Drag window (in editor or full page view) to see the effect. &rarr;</p>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @music.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @music.description %>
</p>



<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>